# Site settings
title: "fokt"
bye_message: "Thx!"
baseurl: "/blog/"
url: "https://fachrioktavian.github.io"
#disqus: fokt
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: fokt

# Build settings
markdown: kramdown
permalink: /:categories/:title/
